#!/bin/sh

export TMPDIR=/home/ant/Web-CASB_tiny/tmp

# OK for early dev:  plackup -l  192.168.1.1:9090    bin/app.psgi            

# run behind httpd 
plackup --no-default-middleware -s FCGI --listen /var/www/run/fcgi.sock bin/app.psgi
